import { Doctor } from "@/features/appointment/types";

export const branches = [
  { id: "downtown", name: "Downtown Medical Center" },
  { id: "northside", name: "Northside Clinic" },
  { id: "westend", name: "West End Hospital" },
];

export const doctors: Doctor[] = [
  {
    id: "dr-smith",
    name: "Dr. Smith",
    specialty: "Cardiologist",
    image: "/dr-smith.jpg",
    availableDays: ["Monday", "Wednesday", "Friday"],
    timeSlots: ["9:00 AM", "10:30 AM", "2:00 PM", "3:30 PM"],
    branchId: "downtown",
    chamberNo: "101",
    floor: "1st",
    address: "123 Downtown St, City",
  },
  {
    id: "dr-jane",
    name: "Dr. Jane",
    specialty: "Cardiologist",
    image: "/dr-jane.jpg",
    availableDays: ["Monday", "Wednesday", "Friday"],
    timeSlots: ["9:00 AM", "10:30 AM", "2:00 PM", "3:30 PM"],
    branchId: "downtown",
    chamberNo: "102",
    floor: "1st",
    address: "123 Downtown St, City",
  },
  {
    id: "dr-kamal",
    name: "Dr. Kamal",
    specialty: "Cardiologist",
    image: "/dr-kamal.jpg",
    availableDays: ["Monday", "Wednesday", "Friday"],
    timeSlots: ["9:00 AM", "10:30 AM", "2:00 PM", "3:30 PM"],
    branchId: "downtown",
    chamberNo: "103",
    floor: "1st",
    address: "123 Downtown St, City",
  },
  {
    id: "dr-johnson",
    name: "Dr. Michael Johnson",
    specialty: "Neurologist",
    image: "/dr-johnson.jpg",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    timeSlots: ["8:00 AM", "11:00 AM", "1:00 PM", "4:00 PM"],
    branchId: "northside",
    chamberNo: "201",
    floor: "2nd",
    address: "456 Northside Ave, City",
  },
  {
    id: "dr-oliver",
    name: "Dr. Michael Oliver",
    specialty: "Neurologist",
    image: "/dr-oliver.jpg",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    timeSlots: ["8:00 AM", "11:00 AM", "1:00 PM", "4:00 PM"],
    branchId: "northside",
    chamberNo: "202",
    floor: "2nd",
    address: "456 Northside Ave, City",
  },
  {
    id: "dr-williams",
    name: "Dr. Emily Williams",
    specialty: "Dermatologist",
    image: "/dr-williams.jpg",
    availableDays: ["Monday", "Tuesday", "Thursday"],
    timeSlots: ["9:30 AM", "11:30 AM", "2:30 PM", "4:30 PM"],
    branchId: "westend",
    chamberNo: "301",
    floor: "3rd",
    address: "789 West End Rd, City",
  },
];
